# collectstatic-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "django.fullname" . }}-collectstatic-job-{{ randAlpha 6 | lower }}
  labels:
    app.kubernetes.io/name: {{ include "django.fullname" . }}
    helm.sh/chart: {{ include "django.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        command: ['python3', 'manage.py', 'collectstatic', '--noinput', '--ignore', 'node_modules']
        envFrom:
          - configMapRef:
              name: {{ include "django.fullname" . }}-config
      restartPolicy: Never
  backoffLimit: 4
  ttlSecondsAfterFinished: 100
