# rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.fullname" . }}-rbac
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "app.fullname" . }}
rules:
  {{- if .Values.configMapPermissions.enabled }}
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update", "patch"]
  {{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "app.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "app.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "app.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
  
