apiVersion: v1
entries:
  cs-helper:
  - apiVersion: v2
    appVersion: "1"
    created: "2024-11-07T21:49:01.756768516+08:00"
    description: A Helm chart for Kubernetes
    digest: 016fb4e6a40f8183e7bc58cd7684249859c118870f7dfb97e52152babeaf0d1c
    name: cs-helper
    type: application
    urls:
    - https://asians-cloud.github.io/uat/gaius-helm/charts/cs-helper-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: "1"
    created: "2024-11-07T21:49:01.756412295+08:00"
    description: A Helm chart for Kubernetes
    digest: e6feaf7efaccf0f77e9ef8dabb325ed212fb141cb759f02bc08ac0d11c53f959
    name: cs-helper
    type: application
    urls:
    - https://asians-cloud.github.io/uat/gaius-helm/charts/cs-helper-0.0.1.tgz
    version: 0.0.1
  www:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-11-07T21:49:01.757112541+08:00"
    description: A Helm chart for Kubernetes
    digest: f165ecef086478046b55adaa98c135973b541343dfd72a9b6b0b72243c0f2621
    name: www
    type: application
    urls:
    - https://asians-cloud.github.io/uat/gaius-helm/charts/www-0.1.0.tgz
    version: 0.1.0
generated: "2024-11-07T21:49:01.755919354+08:00"
