apiVersion: v1
entries:
  cs-helper:
  - apiVersion: v2
    appVersion: "1"
    created: "2024-11-07T17:13:30.750390227+08:00"
    description: A Helm chart for Kubernetes
    digest: cb6a3d4fc1737ed99b1dd0d31ed86b00c38d4f72ceed5f488328466d99bbc766
    name: cs-helper
    type: application
    urls:
    - https://asians-cloud.github.io/uat/gaius-helm/charts/cs-helper-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: "1"
    created: "2024-11-07T17:13:30.7498064+08:00"
    description: A Helm chart for Kubernetes
    digest: e6feaf7efaccf0f77e9ef8dabb325ed212fb141cb759f02bc08ac0d11c53f959
    name: cs-helper
    type: application
    urls:
    - https://asians-cloud.github.io/uat/gaius-helm/charts/cs-helper-0.0.1.tgz
    version: 0.0.1
  www:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-11-07T17:13:30.750904085+08:00"
    description: A Helm chart for Kubernetes
    digest: 025741266fe5b3281d311479f905da5d777810a990d616b2c96e002e0be0b34f
    name: www
    type: application
    urls:
    - https://asians-cloud.github.io/uat/gaius-helm/charts/www-0.1.0.tgz
    version: 0.1.0
generated: "2024-11-07T17:13:30.749337331+08:00"
