apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "app.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- with .Values.env }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
