apiVersion: v1
entries:
  django-celery:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-06-13T14:44:09.915547+08:00"
    description: Celery template kubernetes for Gaius Project
    digest: 7a422f9e68e4d850a294b8e6b7e9fe3185d2f62b20fb22c7e2f06fd09a38f4bb
    name: django-celery
    type: application
    urls:
    - https://asians-cloud.github.io/django-helm/charts/django-celery-0.1.7.tgz
    version: 0.1.7
  django-django:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-06-13T14:44:09.915987+08:00"
    description: A Helm chart for Kubernetes
    digest: bbff55912054792979e49592fba8217e4a27b54422b951bc13036a707841b4fa
    name: django-django
    type: application
    urls:
    - https://asians-cloud.github.io/django-helm/charts/django-django-0.1.7.tgz
    version: 0.1.7
generated: "2022-06-13T14:44:09.915005+08:00"
