apiVersion: v1
entries:
  django:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-06-13T13:42:20.927043+08:00"
    description: A Helm chart for Kubernetes
    digest: dd36e29467f20a0297539b64c41649aa12e8ded84328513787f179998dface17
    name: django
    type: application
    urls:
    - https://asians-cloud.github.io/django-helm/charts/django-0.1.3.tgz
    version: 0.1.3
generated: "2022-06-13T13:42:20.926375+08:00"
